apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-deploy
  name: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-deploy
    spec:
      containers:
      - image: mrboom.azurecr.io/sampleapp:887560bcbe59c39b365657d4d58b658373017241
        name: test
        resources: {}
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: azure-image
