on:
  push:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_PASSWORD }}
      - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
      - name: Change Deployment Image
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'kubernetes/deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: '${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}'
          commitChange: true
          branch: 'master'
          message: 'Update deployment image to ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}'
      - name: view updated deployment file
        run: cat kubernetes/deployment.yaml

