on:
  push:
    branches:
      - master

jobs:
  docker_build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_PASSWORD }}

    - name: Build and push image
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

    - name: Checkout GitOps repo
      uses: actions/checkout@v4
      with:
        repository: Mrboom003/ImageTest
        path: ImageTest

    - name: Update GitOps Repository
      run: |
        cd ImageTest/kubernetes

        sed -i "s|image: mrboom.azurecr.io/sampleapp:.*|image: mrboom.azurecr.io/sampleapp:${{ github.sha }}|g" deployment.yaml

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit -m "Update image to ${{ github.sha }}"
        git push

